### ISSUE TITLE
Error when tryig to install on erpnext v15

### ISSUE THREAD

**Issue by showlinepos** [half-ware/newara#2]
[4d](https://discuss.frappe.io/t/odoo-like-theme-for-frappe/127737/13?u=francis1)
ERROR: [Errno 2] No such file or directory: ‘/home/frappe1/frappe-bench/apps/newara/setup.py’
Traceback (most recent call last):
File “/usr/local/bin/bench”, line 8, in
sys.exit(cli())
File “/usr/local/lib/python3.10/dist-packages/bench/cli.py”, line 132, in cli
bench_command()
File “/usr/local/lib/python3.10/dist-packages/click/core.py”, line 1157, in call
return self.main(*args, **kwargs)
File “/usr/local/lib/python3.10/dist-packages/click/core.py”, line 1078, in main
rv = self.invoke(ctx)
File “/usr/local/lib/python3.10/dist-packages/click/core.py”, line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File “/usr/local/lib/python3.10/dist-packages/click/core.py”, line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File “/usr/local/lib/python3.10/dist-packages/click/core.py”, line 783, in invoke
return __callback(*args, **kwargs)
File “/usr/local/lib/python3.10/dist-packages/bench/commands/make.py”, line 181, in get_app
get_app(
File “/usr/local/lib/python3.10/dist-packages/bench/app.py”, line 777, in get_app
app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
File “/usr/local/lib/python3.10/dist-packages/bench/utils/render.py”, line 126, in wrapper_fn
return fn(*args, **kwargs)
File “/usr/local/lib/python3.10/dist-packages/bench/app.py”, line 247, in install
app_name = get_app_name(self.bench.name, self.app_name)
File “/usr/local/lib/python3.10/dist-packages/bench/utils/app.py”, line 249, in get_app_name
with open(setup_py_path, “rb”) as f:
FileNotFoundError: [Errno 2] No such file or directory: ‘/home/frappe1/frappe-bench/apps/newara/setup.py’
frappe1@vmi1947963:~/frappe-bench$

**Comment by showlinepos** [comment]
this error have been resolved l used bench --site {sitename } install-app newara

**Comment by showlinepos** [comment]
Now after succefully installing there are no changes showing in my instance its still white as usual

**Comment by half-ware** [comment]
Try execute **bench build**

**Comment by half-ware** [comment]
bench --site {sitename } uninstall-app newara
bench --site {sitename } remove-app newara
Download 1.1.3 and try again

**Comment by showlinepos** [comment]
now working fine keep it up the theme is very super
